# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchRepository' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SearchRepository

  # RxSwift
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  
  # Alamofire + ObjectMapper
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'AlamofireNetworkActivityLogger'
  
  # IndicatorView
  pod 'NVActivityIndicatorView'

  target 'SearchRepositoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
